-- SCRIPT TO DROP ALL THE CURRENT TABLES, CREATE THEM AGAIN AND ADD SAMPLE DATA
-- DROP ALL TABLES IF THEY EXIST
DROP TABLE IF EXISTS MaterialesRecomendados;

DROP TABLE IF EXISTS MaterialesSalas;

DROP TABLE IF EXISTS ReservacionesMateriales;

DROP TABLE IF EXISTS Reservaciones;

DROP TABLE IF EXISTS Experiencias;

DROP TABLE IF EXISTS Mesas;

DROP TABLE IF EXISTS Salas;

DROP TABLE IF EXISTS Materiales;

DROP TABLE IF EXISTS UsuariosLogros;

DROP TABLE IF EXISTS Logros;

DROP TABLE IF EXISTS HistorialPrioridad;

DROP TABLE IF EXISTS GruposUsuarios;

DROP TABLE IF EXISTS Credenciales;

DROP TABLE IF EXISTS Usuarios;

DROP TABLE IF EXISTS UnidadesFormacion;

DROP TABLE IF EXISTS Estatus;